import Evento from '../eventInformation/types';

const eventosExemplo: Evento[] = [
  {
    cdevento: 1,
    tipoEvento: 'Concerto',
    descricao: 'Lorem',
    dtEvento: new Date('2024-12-01'),
    nomeEvento: 'Concerto de Verão',
    localEvento: 'Parque Central',
    faixaEtaria: 0,
    imagemUrl:
      'https://me-gestao-imagens.s3.amazonaws.com/minhaentrada/gestao/fotos/24166_banner6.jpg',
    aberturaEvento: '16:00',
    inicioEvento: '19:00',
    capacidade: 5000,
    qtdIngressos: 3000,
  },
  {
    cdevento: 2,
    tipoEvento: 'Festival',
    descricao:
      'Festival de Jazz ao Ar Livre - uma noite de jazz com músicos internacionais e locais.',
    dtEvento: new Date('2024-11-15'),
    nomeEvento: 'Jazz no Parque',
    localEvento: 'Praça da Música',
    faixaEtaria: 0,
    imagemUrl:
      'https://me-gestao-imagens.s3.amazonaws.com/minhaentrada/gestao/fotos/24166_banner6.jpg',
    aberturaEvento: '18:00',
    inicioEvento: '20:00',
    capacidade: 4000,
    qtdIngressos: 2500,
  },
  {
    cdevento: 3,
    tipoEvento: 'Show',
    descricao: 'Show exclusivo com banda famosa em arena coberta.',
    dtEvento: new Date('2024-10-20'),
    nomeEvento: 'Turnê Pop Rock',
    localEvento: 'Arena Central',
    faixaEtaria: 16,
    imagemUrl:
      'https://me-gestao-imagens.s3.amazonaws.com/minhaentrada/gestao/fotos/24166_banner6.jpg',
    aberturaEvento: '19:00',
    inicioEvento: '21:00',
    capacidade: 10000,
    qtdIngressos: 8000,
  },
  {
    cdevento: 4,
    tipoEvento: 'Concerto',
    descricao: 'Concerto clássico ao ar livre com orquestra sinfônica.',
    dtEvento: new Date('2024-12-20'),
    nomeEvento: 'Noite Clássica',
    localEvento: 'Parque da Harmonia',
    faixaEtaria: 0,
    imagemUrl:
      'https://me-gestao-imagens.s3.amazonaws.com/minhaentrada/gestao/fotos/24166_banner6.jpg',
    aberturaEvento: '17:00',
    inicioEvento: '19:30',
    capacidade: 6000,
    qtdIngressos: 4500,
  },
  {
    cdevento: 5,
    tipoEvento: 'Feira',
    descricao:
      'Feira de gastronomia local com food trucks e apresentações culturais.',
    dtEvento: new Date('2024-11-25'),
    nomeEvento: 'Gastro Fest',
    localEvento: 'Parque Gastronômico',
    faixaEtaria: 0,
    imagemUrl:
      'https://me-gestao-imagens.s3.amazonaws.com/minhaentrada/gestao/fotos/24166_banner6.jpg',
    aberturaEvento: '12:00',
    inicioEvento: '12:00',
    capacidade: 2000,
    qtdIngressos: 1500,
  },
  {
    cdevento: 6,
    tipoEvento: 'Palestra',
    descricao: 'Palestra com autor best-seller sobre desenvolvimento pessoal.',
    dtEvento: new Date('2024-09-10'),
    nomeEvento: 'Transformação Pessoal',
    localEvento: 'Centro de Convenções',
    faixaEtaria: 18,
    imagemUrl:
      'https://me-gestao-imagens.s3.amazonaws.com/minhaentrada/gestao/fotos/24166_banner6.jpg',
    aberturaEvento: '09:00',
    inicioEvento: '10:00',
    capacidade: 300,
    qtdIngressos: 200,
  },
  {
    cdevento: 7,
    tipoEvento: 'Exposição',
    descricao: 'Exposição de arte moderna com obras de artistas locais.',
    dtEvento: new Date('2024-08-05'),
    nomeEvento: 'Arte Moderna',
    localEvento: 'Museu de Arte',
    faixaEtaria: 0,
    imagemUrl:
      'https://me-gestao-imagens.s3.amazonaws.com/minhaentrada/gestao/fotos/24166_banner6.jpg',
    aberturaEvento: '10:00',
    inicioEvento: '10:00',
    capacidade: 1000,
    qtdIngressos: 800,
  },
  {
    cdevento: 8,
    tipoEvento: 'Festival',
    descricao: 'Festival de cinema ao ar livre com projeções de clássicos.',
    dtEvento: new Date('2024-09-15'),
    nomeEvento: 'Cinema na Praça',
    localEvento: 'Praça Central',
    faixaEtaria: 12,
    imagemUrl:
      'https://me-gestao-imagens.s3.amazonaws.com/minhaentrada/gestao/fotos/24166_banner6.jpg',
    aberturaEvento: '18:00',
    inicioEvento: '19:00',
    capacidade: 500,
    qtdIngressos: 500,
  },
  {
    cdevento: 9,
    tipoEvento: 'Workshop',
    descricao: 'Workshop de fotografia com profissional renomado.',
    dtEvento: new Date('2024-10-12'),
    nomeEvento: 'Fotografia Criativa',
    localEvento: 'Estúdio Artístico',
    faixaEtaria: 15,
    imagemUrl:
      'https://me-gestao-imagens.s3.amazonaws.com/minhaentrada/gestao/fotos/24166_banner6.jpg',
    aberturaEvento: '14:00',
    inicioEvento: '15:00',
    capacidade: 50,
    qtdIngressos: 40,
  },
  {
    cdevento: 10,
    tipoEvento: 'Conferência',
    descricao:
      'Conferência sobre inovação e tecnologia com palestrantes internacionais.',
    dtEvento: new Date('2024-11-01'),
    nomeEvento: 'Inova Tech',
    localEvento: 'Centro Tecnológico',
    faixaEtaria: 18,
    imagemUrl:
      'https://me-gestao-imagens.s3.amazonaws.com/minhaentrada/gestao/fotos/24166_banner6.jpg',
    aberturaEvento: '08:00',
    inicioEvento: '09:00',
    capacidade: 2000,
    qtdIngressos: 1500,
  },
];

export default eventosExemplo;
